config-version: 1

root-folder: migrations

snowflake_account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
snowflake_role: "{{ env_var('SNOWFLAKE_ROLE') }}"
snowflake_warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"

snowflake_database: METADATA

snowflake_schema: SCHEMACHANGE

change-history-table: CHANGE_HISTORY

create-change-history-table: true