config-version: 1

root-folder: migrations

snowflake-account: ${SNOWFLAKE_ACCOUNT}
snowflake-user: SVC_SNOWFLAKE_DEPLOY
snowflake-role: ${SNOWFLAKE_ROLE}
snowflake-warehouse: ${SNOWFLAKE_WAREHOUSE}
snowflake-database: SNOWFLAKE
snowflake-schema: PUBLIC

change-history-table: CHANGE_HISTORY
