config-version: 1

root-folder: migrations/to_be_deployed

snowflake-account: ${SNOWFLAKE_ACCOUNT}
snowflake-user: SVC_SNOWFLAKE_DEPLOY
snowflake-role: ${SNOWFLAKE_ROLE}
snowflake-warehouse: ${SNOWFLAKE_WAREHOUSE}
snowflake-database: ${SNOWFLAKE_DATABASE}
snowflake-schema: ${SNOWFLAKE_SCHEMA}

change-history-table: CHANGE_HISTORY
